### ISSUE TITLE
Bug: Firestore listId is null upon app loading / flashing of Home

### ISSUE THREAD

**Issue by connietran-dev** [the-collab-lab/tcl-26-smart-shopping-list#29]
Upon loading the app, listId is null - as shown in console in screenshot below. 

![image](https://user-images.githubusercontent.com/61371242/127588615-2f1d33ff-a37f-4e93-ae17-bc14a2004807.png)

Corresponding console.log's and code shown in screenshot below.

![image](https://user-images.githubusercontent.com/61371242/127588676-89ef760c-9c6e-4c40-9f26-42d30c6a2aae.png)

token and listId also seem to be loading twice

The Home also flashes before redirecting you.

**Comment by anderswift** [comment]
I think this is happening because we're not accounting for setting the state being async.
